#-----------------------------------------------------------------------------
#  Configuration
#-----------------------------------------------------------------------------
COMPONENT_NAME = "{{cookiecutter.package_name}}"

IMPORTED_KICADLIBS = [
("#imported/kicadlib_macrofab", 'https://bitbucket.org/eyob/kicadlib_macrofab.git', "v0.3")
]


#-----------------------------------------------------------------------------
#  Call shared common script
#-----------------------------------------------------------------------------
SConscript(MakooCommonScript("kicad"),
           exports=['COMPONENT_NAME', 'IMPORTED_KICADLIBS'])
           
